### ISSUE TITLE
Should it be possible to pass multiple arguments to a filter ?

### ISSUE THREAD

**Issue by DavidGoodwin** [mistic100/PHP-Hooks#4]
Hi,
This seems to work  : 

```php
  public function testMultipleArgumentsToFilter()
  {

    self::$hooks->add_filter('html', function($tag, $name) { return ["a:$tag", "a:$name"]; }, 20);

    $retval = self::$hooks->apply_filters('html', 'arg1', 'arg2');

    $this->assertEquals($retval, ['a:arg1', 'a:arg2']);
  }
```

But if you attempt to have two filters registered, there's an array-to-string-conversion error in Hooks.php on line ~296.

```php

  public function testMultipleFiltersMultipleArguments()
  {

    self::$hooks->add_filter('html', function($tag, $name) { return ["a:$tag", "a:$name"]; }, 20);
    self::$hooks->add_filter('html', function($tag, $name) { return ["b:$tag", "b:$name"]; }, 10);

    $retval = self::$hooks->apply_filters('html', 'arg1', 'arg2');

    $this->assertEquals($retval, ['a:b:arg1', 'a:b:arg2']);
  }
```

**Comment by mistic100** [comment]
Yes it should work. I don't touch PHP anymore, feel free to submit a PR if you find the issue.

**Comment by DavidGoodwin** [comment]
OK.... I'll see what I can do.
(Perhaps you should mark the project as abandoned on packagist etc? https://packagist.org/packages/mistic100/php-hooks )

**Comment by DavidGoodwin** [comment]
Ah - the problem is actually that I should be only returning one value from the function (and the other args are just optional things ... but aren't also changed by the filter).

**Comment by mistic100** [comment]
Sorry I didn't read your code correctly the first time.
